version: "3"

services:
  mysql:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./:/app
    environment:
      MYSQL_ROOT_PASSWORD: "${DATABASE_PASSWORD}"

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - ${PHPMYADMIN_PORT}:80
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql

  app:
    build:
      context: ./
      dockerfile: docker/php/Dockerfile
    depends_on:
      - mysql
    restart: always
    user: "1000"
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - ./:/app
    env_file:
      - .env
    command: "php -S 0.0.0.0:${SERVER_PORT} -t public public/index.php"
